### ISSUE TITLE
Sort vote log on personal page by date

### ISSUE THREAD

**Issue by p16i** [codeforthailand/politician-directory#102]
Currently the log is sorted by date ascending. IMO, the latest vote should come first.

https://pedantic-edison-3897de.netlify.com/people/กรณิศ-งามสุคนธ์รัตนา

<img width="715" alt="image" src="https://user-images.githubusercontent.com/1214890/68550162-bcaa2600-0400-11ea-83f9-232e202dc919.png">

@rapee I think this should also be included in the first milestone.

**Comment by thasarito** [comment]
will fix this soon.
