### ISSUE TITLE
Support social sharing

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#107]
It should show correct page title / description / cover image when shared on:

- Facebook

Og title : They Work For Us รู้จักและติดตาม 'ผู้แทน' ในสภาของเรา
Og Description : ใครเป็นใคร เคยทำอะไรมาบ้าง ตอนนี้อยู่ตำแหน่งไหน และยกมือสนับสนุนอะไรในสภา
Og Image: depends on page

- Default : ค้นหา ตรวจสอบ โปร่งใส ผู้แทนของเราคือใคร และทำอะไรเพื่อเรา
- /people* : เป็นใคร มาจากไหน ทำตามที่เคยหาเสียงไว้หรือเปล่า? ชวนติดตามผู้แทนของเราในสภา
- /party* : งูเห่ามีไหม? แตกแถวหรือเปล่า? ชวนดูภาพรวมพรรคและสภาในการเมืองไทย
- /votelog* : ใครหนุน ใครค้าน? สรุปการลงมติครั้งสำคัญในสภา

![cover-home](https://user-images.githubusercontent.com/924635/69112300-7e70ce80-0ab2-11ea-9b3e-15e7c6ca5aea.png)
![cover-people](https://user-images.githubusercontent.com/924635/69112297-7dd83800-0ab2-11ea-90df-5e6258c280d7.png)
![cover-party](https://user-images.githubusercontent.com/924635/69112299-7e70ce80-0ab2-11ea-9cad-e482aa820f98.png)
![cover-votelog](https://user-images.githubusercontent.com/924635/69112301-7e70ce80-0ab2-11ea-9e62-42daef1ba4a0.png)

**Comment by mixth** [comment]
I'm not sure which image or title shall be used in which pages. Do we have a design for that?

**Comment by rapee** [comment]
Design team is working on this. Will update more details later today.

**Comment by rapee** [comment]
@mixth Can you work on this?

**Comment by mixth** [comment]
@rapee Sure thing 😀

One thing, on title the project is named "They Work For Us", while in the image is subbed "They Work For You".

**Comment by rapee** [comment]
Let me consult the title with content team. @mixth
