### ISSUE TITLE
[idea]  Contact Information of each MP

### ISSUE THREAD

**Issue by c4n** [codeforthailand/politician-directory#15]
I think it would be nice If we could have a website that contains contact information of each MP.  
e.g. https://www.parliament.uk/mps-lords-and-offices/mps/

I was walking around Bon Kai neighborhood the other day and came across this poster that contains contact information of the MP of that electoral district. I thought that if we could collect contact information of all MPs in Thailand, it would be a valuable resource for those who want to voice out their concern locally/nationally.
![image](https://user-images.githubusercontent.com/4990317/67031611-17bb6680-f13c-11e9-9f2e-adce44be685e.png)

**Comment by rapee** [comment]
Thanks for the idea. I think that's very useful. Currently we're prepping dataset, you can take a look at https://github.com/codeforthailand/politician-directory/blob/master/src/contents/people.yaml. What's missing is phone number.

**Comment by rapee** [comment]
Added fields. Next step is to gather contact information.
