### ISSUE TITLE
Create Motion top page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#161]
# What To Do

URL: `/motions`

- New motion top page
  - Layout, UI and static content as seen in the design
  - Top right visualization should be mocked. Will implement in #165 .
  - List motion categories:
     - [All categories](https://docs.google.com/spreadsheets/d/17Id4tAdNJDtNpbaaZco3CTMGlUkGoVILkFoc-TENtN4/edit#gid=877287671) *Need update for category hierarchy.
- Track user behavior. See details in #168.

## Data Set

- [Motions](https://docs.google.com/spreadsheets/d/17Id4tAdNJDtNpbaaZco3CTMGlUkGoVILkFoc-TENtN4/edit#gid=1593490955)

# Design

Mobile
https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/409314650

Desktop
https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/408750962

**Comment by rapee** [comment]
@mixth Can you work on this?

**Comment by mixth** [comment]
Sure! I will start with this one.

**Comment by mixth** [comment]
@rapee I'm not sure how to design the category and subcategory. Shall I create new sheet for this in the spreadsheet and then import it as yaml as well?
