### ISSUE TITLE
Create motion detail view page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#163]
# What To Do

URL: `/motions/:id`

- Create motion detail view page
  - เลขทะเบียนรับ (Motion registration no.)
  - วันที่เสนอ (Proposal date)
  - วันที่ประชุม (Vote date)
  - สถานะของญัตติ (Status)
  - สาระและวัตถุประสงค์ (Content)
  - ผู้รับรอง (Proposer and Seconders. On mobile, popup will be done #167)
  - ผลการลงมติ
    - link บันทึกการลงมติ (Vote link)
    - แสดงข้อความผลการลงมติ (vote result)
    - แสดง grid ของผู้ลงมติ ถ้ามีข้อมูลจาก votelog (people vote)
    - ข้อมูลแต่งตั้งคณะกรรมาธิการ Join (ด้วย select committee) กับ [People dataset](https://docs.google.com/spreadsheets/d/1kcom8zgR-FMCGu78bCwilxq5-GrE4NVr5cE4L7geUuo/edit#gid=1739107794) (`committee.xxx.set`)
      - ชื่อ
      - พรรคการเมือง (ถ้ามี บางคนจะเป็นคนธรรมดา)
      - ตำแหน่งใน กมธ. นี้
- Pagination: previous / next motions will be implemented by #166 .

## Data Set

- [Motions](https://docs.google.com/spreadsheets/d/17Id4tAdNJDtNpbaaZco3CTMGlUkGoVILkFoc-TENtN4/edit#gid=1593490955)
- [People](https://docs.google.com/spreadsheets/d/1kcom8zgR-FMCGu78bCwilxq5-GrE4NVr5cE4L7geUuo/edit#gid=1739107794)
- [VoteLog](https://docs.google.com/spreadsheets/d/1kcom8zgR-FMCGu78bCwilxq5-GrE4NVr5cE4L7geUuo/edit#gid=1873669969)

# Design

Mobile
https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/409314656

Desktop
https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/407960009

**Comment by rapee** [comment]
@thasarito Can you work on this?

**Comment by thasarito** [comment]
look like motion don't have unique id kub
