### ISSUE TITLE
Install tracking code for research on user behavior

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#168]
# How

In this milestone, we want to gain insights on what motivated people to get interested in Thai politics. In this research, we'll measure between 2 focused topics: Persons and Social Problems. 

## [A] People being interested in politics because they focus on:

1. **Persons (บุคคล)**: We implied users are motivated by social problems when they click to see  "people" (บุคคล, นักการเมือง) the first time when they are on landing page.
2. **Social Problems (ประเด็น)**: We implied users are motivated by social problems when they click to see "motions" (ญัตติ) the first time when they are on landing page.

In later sessions, we won't change user's focused topics even if users clicked other link.

#  What To Do

- Put website visitors into one of the two segments in [A].
- We'll use Google Analytics.
- On landing page, if they're first time visitors, we'll track the first link they choose between 1. Politicians (`/people`) and 2. Motions (`/motion`). This can be done by setting **custom dimension 1** to `"people"` or `"motion"` along with event tracking.
- We won't set custom dimension if it has been set on the user before. This can be done with cookie or local storage.
- This user segmentation will be as reliable as how good Google Analytics can track the same user across devices.
- Con: if users switched device, they'll lose cookie and local storage, and thus possible to reset **custom dimension**.

**Comment by thasarito** [comment]
Want to take this issue and also #169  kub. But need more guidance.

**Comment by p16i** [comment]
sounds like we can look at GA's behavior flow:
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/1214890/82114380-d5ebb080-975c-11ea-874b-e4db0d3ea357.png">.

I guess we might have to create a new user segment for new visitors. If GA provides such an  attributes, this is quite straightforward to do without coding involved, otherwise we might need to send a custom event to GA for new users.

**Comment by rapee** [comment]
@heytitle I think we can use [custom dimension](https://support.google.com/analytics/answer/2709828#scope). Let say we create a new dimension called "Focused Topic" (dimension1), we can set like this:

```js
// Set focused topic
const focus = getFocusedTopic(); // "people", "motion"
ga('set', 'dimension1', focus);

// Dimension will be tracked on top of event or page view
ga('send', 'event', 'Topic', focus);
```

In the report, we'll be able to filter or segment by this dimension.
