### ISSUE TITLE
Split name fields semantically by title, first name and last name

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#171]
# What To Do

Some people's name cells in the data sheets are merged e.g. "พลตำรวจเอกเสรีพิศุทธ์  เตมียเวส".

We want to split it into 3 fields:

- Title: พลตำรวจเอก
- First name: เสรีพิศุทธ์
- Last name: เตมียเวส

Common titles are easy to catch: นาย, นาง, นางสาว and if it's written in full.

But others can be more difficult such as abbreviations. It may has many representations, e.g. ร.ท. (ร้อยโท, เรือโท, เรืออากาศโท) 

Our goal is to split up names in [Motion dataset]()'s proposers and seconders.

# Read more

- [ยศทหารและตำรวจไทย](https://th.wikipedia.org/wiki/%E0%B8%A2%E0%B8%A8%E0%B8%97%E0%B8%AB%E0%B8%B2%E0%B8%A3%E0%B9%81%E0%B8%A5%E0%B8%B0%E0%B8%95%E0%B8%B3%E0%B8%A3%E0%B8%A7%E0%B8%88%E0%B9%84%E0%B8%97%E0%B8%A2)

**Comment by rapee** [comment]
@mixth Can you work on this?

**Comment by mixth** [comment]
I'm taking this one while waiting for the resources for `/motions`.
