### ISSUE TITLE
Hero section on homepage

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#20]
Implement hero section on homepage

- [x]  Title and subtitle (Done)
- [x] 3 features (image + text) with placeholder link (e.g. href="#")
- [x] About Us button (Done)

For the 3 features, please use this mock icon

![loupe](https://user-images.githubusercontent.com/924635/67143942-36843f00-f29b-11e9-9439-9800eb95f917.png)

<div>Credit: Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"             title="Flaticon">www.flaticon.com</a></div>

### Design Reference

[Landing Page](https://projects.invisionapp.com/d/main#/console/18605293/387144381/preview)

Click "Inspect Mode" for style attribute information

**Comment by reobin** [comment]
Taking this up

**Comment by rapee** [comment]
Thanks!
