### ISSUE TITLE
Create <VoteLogCard/> React component and add to homepage

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#22]
Create `<VoteLogCard/>` React component to be used on homepage and vote record list page.

Homepage: showing a list of **vote logs (ผลการลงมติ)** ordered by the most recent log. 

This issue needs you to create **only UI component with mock data**. We'll have another issue for data binding. (#23)

For horizontal stacked bar chart, it's displaying ratio of type of casted vote, e.g.

- เห็นด้วย approve
- ไม่เห็นด้วย disprove
- งดออกเสียง abstained
- ขาดประชุม absent

Refer to `src/contents/votelog.yml` for data reference.

<img width="662" alt="Screen Shot 2019-10-19 at 18 19 55" src="https://user-images.githubusercontent.com/924635/67144330-7fd68d80-f29f-11e9-811a-c3e7e9c00d82.png">

### Design Reference

- [Landing Page](https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/387144381)
- [Vote Record List Page](https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/387144387)

Click "Inspect Mode" for style attribute information

Related Issues
- #23

**Comment by tanat44** [comment]
im working on this

**Comment by rapee** [comment]
Thanks!

**Comment by tanat44** [comment]
:
