### ISSUE TITLE
Create <Footer/> component

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#24]
Create footer component as in https://elect.in.th.

<img width="722" alt="Screen Shot 2019-10-19 at 18 20 19" src="https://user-images.githubusercontent.com/924635/67144763-b82c9a80-f2a4-11e9-9232-2bed93dcff67.png">

### Design Reference

- [Landing Page](https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/387144381)
- [Vote Record List Page](https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/387144387)

Click "Inspect Mode" for style attribute information

**Comment by ricardoham** [comment]
Could I pick this issue?

**Comment by rapee** [comment]
@ricardoham Sure! Thanks in advance.

**Comment by p16i** [comment]
We should also have copyright or license for data and other relevant usages.

@unnawut any suggestion?

**Comment by akankshajai** [comment]
I would like to work on this.

**Comment by rapee** [comment]
This issues has been merged. Thanks all!

@heytitle @unnawut  Fire up a new issue if you want to add more info.
