### ISSUE TITLE
Update <Header/> component

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#25]
Update header as per design.  In this issue we only need a static link for Search button (#10), language switcher (#2), hamburger menu (#5).

<img width="1184" alt="Screen Shot 2019-10-19 at 19 22 55" src="https://user-images.githubusercontent.com/924635/67144855-e3fc5000-f2a5-11e9-8d1e-c2d42744c14b.png">

### Design Reference

- [Landing Page](https://projects.invisionapp.com/d/main#/console/18605293/387144381/preview)
- [Vote Record List Page](https://projects.invisionapp.com/d/main#/console/18605293/387144387/preview)

Click "Inspect Mode" for style attribute information

**Comment by reobin** [comment]
Taking this up (for the style anyway)

**Comment by rapee** [comment]
Thanks!
