### ISSUE TITLE
Add environment label

### ISSUE THREAD

**Issue by p16i** [codeforthailand/politician-directory#29]
It would be good if users know which environment, i.e. dev or production, they're visiting.

For example, right now we only have a dev environment. We should tell them explicitly that what they're seeing is in development and things might not be 100% ready. 

One possible solution is to have a component that check an environment variable that has a different value for each environment.

We might use this plugin for environment variable sharing: https://www.gatsbyjs.org/packages/gatsby-plugin-env-variables/.

**Comment by rapee** [comment]
I use `NODE_ENV` which supported out-of-box.

**Comment by rapee** [comment]
Sorry, changed to `GATSBY_ENV` because above didn't work on `gatsby build`.

**Comment by p16i** [comment]
Great!
