### ISSUE TITLE
Prepare initial dataset

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#3]
Dataset we need for bootstrapping:

1. People (Cabinet, MP, Senate) ข้อมูลบุคคล
2. Party พรรคการเมือง
3. VoteLog การลงมติ
4. PeopleVote ใครโหวตอะไรใรแต่ละการลงมติ

**Comment by c4n** [comment]
It would be great, if you could include their contact information as well. See #15

**Comment by rapee** [comment]
Closed by 82bc01e
Closed #15 by 3978f77
