### ISSUE TITLE
Use dash instead of underscore for politician page.

### ISSUE THREAD

**Issue by p16i** [codeforthailand/politician-directory#34]
Hi,

I see that we're using underscore `_` for politician pages; however, google recommends using dash `-` instead of underscore `_` in urls. 

Ref: https://support.google.com/webmasters/answer/76329?hl=en

**Comment by szilard079** [comment]
I'll take this one

**Comment by alam3211** [comment]
can i solve it?

**Comment by rapee** [comment]
@szilard079 Thanks! PR merged.

**Comment by rapee** [comment]
@alam3211 Can you take another one?
