### ISSUE TITLE
Custom color for party page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#38]
Each party page should have custom color taken from `color` field.

Please refer to party color at `https://github.com/codeforthailand/election-live/blob/master/data/party.json`

<img width="1135" alt="Screen Shot 2019-10-26 at 16 45 28" src="https://user-images.githubusercontent.com/924635/67617731-6342d400-f810-11e9-8107-c8aeb3903f0c.png">

**Comment by rajathans** [comment]
I'd like to work on this

**Comment by Surya97** [comment]
Hey, is this issue still open? Can I work on this?

**Comment by rapee** [comment]
Yes, please send PRs.
