### ISSUE TITLE
Custom color for people page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#39]
People page's profile section background should have his/her party color. 

Refer to #38 for details on party color.

<img width="703" alt="Screen Shot 2019-10-26 at 16 48 49" src="https://user-images.githubusercontent.com/924635/67617752-a0a76180-f810-11e9-8d90-245a2c3b0fcf.png">

**Comment by rajathans** [comment]
I'd like to work on this

**Comment by rapee** [comment]
Please @rajathans

**Comment by noimeta** [comment]
i'm working on this one
