### ISSUE TITLE
Stylize and bind data for VoteLog and PeopleVote

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#41]
People's vote has 4 possible state: 

1. เห็นด้วย approve
2. ไม่เห็นด้วย disprove
3. งดออกเสียง abstained
4. ขาดประชุม absent

These are keys to map between entity types

```
People <=(name & lastname )=> PeopleVote

VoteLog <=(id)=(votelog.${id})=> PeopleVote
```

<img width="834" alt="Screen Shot 2019-10-26 at 17 07 20" src="https://user-images.githubusercontent.com/924635/67618034-a3f01c80-f813-11e9-8be8-44ff54399e6a.png">

**Comment by thasarito** [comment]
I'm working on this.

**Comment by rapee** [comment]
@thasarito Cool, thanks in advance.

**Comment by rapee** [comment]
Finally!! :D
