### ISSUE TITLE
Create stacked bar chart visualization <PartyProfileBar /> component for Party Profile

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#42]
Create <PartyProfileBar /> component. This is a horizontal stacked bar chart to display each of party profiles. You can mock data as you like. There will be another issue for binding data.

1. MP Type: party list, district (สส. บัญชีรายชื่อ / แบ่งเขต)
2. Gender
3. Age Range
4. Highest Education Level
5. Occupation Group

<img width="746" alt="Screen Shot 2019-10-26 at 17 14 07" src="https://user-images.githubusercontent.com/924635/67618064-28429f80-f814-11e9-8ff6-6573c48d1ccb.png">

**Comment by SafaElmali** [comment]
Hey hi. I want to work on this but I want to use bootstrap? Can I install it?

**Comment by Th1nkK1D** [comment]
Can I do this?

**Comment by rapee** [comment]
Duplicate of #66. Sorry for confusion.
