### ISSUE TITLE
Add contributor name to credit section in about page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#48]
# Note

This issue is for demonstration to Pull Request for open source project first-timers.

# Todo 

1. Fork this repo to yours.
2. Create branch `add-credit`
3. Add your name as contributor in `src/pages/about.js`
4. Commit and push to your repo
5. Create Pull Request and wait your successful merge!

**Comment by p16i** [comment]
should we have only people who actually contribute something to the project on the about page?

In other words, I would not accept PRs from one who haven't contributed to the project yet.

**Comment by rapee** [comment]
@heytitle I agree. Sorry this was for Open Source workshop the other day and need to clean up later. Close for now.
