### ISSUE TITLE
Build hamburger menu for desktop and mobile

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#5]
Add menu to header. Currently menu design is the same for both screen sizes.

Menu:

- Browse Politician
  - คณะรัฐมนตรี (`/cabinet`)
  - ส.ว. (`/senate`)
  - ส.ส.  (`/representatives`)
- บันทึกมติ (`/votelog`)
- ค้นหา (`/#search`)
- เกี่ยวกับ (`/about`)
- สุ่ม (`/#random`)

Reference design
1. [Menu in Header](https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/387144381)

2. [Desktop: Expanded menu](https://projects.invisionapp.com/share/7HU7PWOYAQM#/screens/389166637)

3. Mobile: Expanded menu (image below)
<img width="368" alt="Screen Shot 2019-11-03 at 15 37 47" src="https://user-images.githubusercontent.com/924635/68082596-5dbd3d80-fe51-11e9-95c9-c6a51351a720.png">

**Comment by cjharkins** [comment]
I'll take this one

**Comment by rapee** [comment]
Anyone wants to help on adding menu items in Thai?

I added menu details in the issue description.

**Comment by rapee** [comment]
I'm working on this.
