### ISSUE TITLE
Script that automatically pull contributors' names from Github and add to About page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#50]
We have contributor names in about page but we need to keep update this party manually.

A script to automatically pull contributors' names from Github would be very good.

**Comment by mixth** [comment]
Interested.

I suggest a build-time pulling from GitHub REST API v3. Since the GraphQL v4 needs authentication token to query anything.

**Comment by mixth** [comment]
I drafted a pull request, which is based on what I have mentioned above. Feel free to comment on the concept and its implementation. 🙂
