### ISSUE TITLE
Replace image on hero section

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#56]
Download assets from #51

![Screen Shot 2019-11-01 at 20 53 17](https://user-images.githubusercontent.com/924635/68029427-c25d8880-fce9-11e9-9326-b39ab8bea528.png)

**Comment by noimeta** [comment]
I'll work on this one!!

**Comment by noimeta** [comment]
Where should I store illus images? Should I rename them to meaningful names?
