### ISSUE TITLE
Build about this site page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#6]

**Comment by p16i** [comment]
We need text for this. I would also like to see all people contributed in this project acknowledged, similar to https://elect.thematter.co/about.

Possibly, in a long run, we might possibly need a script that automatically pull contributors' names from Github.

**Comment by rapee** [comment]
Auto pull contributors has been done #50

**Comment by rapee** [comment]
Close this. Let's update content on #73
