### ISSUE TITLE
Create StackedBarChart component

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#66]
StackedBarChart component is used on Profile section for many pages (Party, Cabinet, Senate, House of Representatives)

It should receive following props:

- data (Array<Object>)
  - name (String) - Category name
  - value (Number) - Count for this category
  - background (String) - Bar background color

```js
[
  { name: "15-24 ปี", value: 142, background: "#eeeeee" },
  { name: "25-38 ปี", value: 362, background: "#cccccc" },
  { name: "39-73 ปี", value: 456, background: "#aaaaaa" },
  { name: "74-91 ปี", value: 12, background: "#666666" }
]
```

Each bar shows category name (e.g. 25-38 ปี), percentage, background color. It should display tooltip (Category name, percentage).

In case bar width is too small to contain label/percentage, the labels should be hidden.

<img width="1090" alt="Screen Shot 2019-11-03 at 15 44 18" src="https://user-images.githubusercontent.com/924635/68082705-68c49d80-fe52-11e9-94a1-b1b191eb7f56.png">

**Comment by mixth** [comment]
I will change my #67 to match this issue. I didn't know that the design hadn't finalized yet.

**Comment by rapee** [comment]
Close this. Continue adding  this component on other pages #71
