### ISSUE TITLE
Add dropdowns to control filter for waffle visualization 

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#69]
Add dropdowns to control data filtering  for waffle visualization on homepage.

Related issue for tooltips #78 

<img width="1090" alt="Screen Shot 2019-11-03 at 16 15 58" src="https://user-images.githubusercontent.com/924635/68082929-5730c500-fe55-11e9-88d2-2e111af48fa2.png">

**Comment by rapee** [comment]
@Th1nkK1D Can you take this issue krub?

**Comment by Th1nkK1D** [comment]
> @Th1nkK1D Can you take this issue krub?

Sure! Gonna take quite a while since I need to do it after work.

**Comment by rapee** [comment]
Related issue: tooltips #78

**Comment by rapee** [comment]
@Th1nkK1D Any updates on this issue?

**Comment by Th1nkK1D** [comment]
> @Th1nkK1D Any updates on this issue?

According to my graduation this week, no updates yet krub ; - ; Sorry that i forget to mention this earlier.

**Comment by rapee** [comment]
OK @Th1nkK1D, I'll assign others to do this for now.

**Comment by Th1nkK1D** [comment]
> OK @Th1nkK1D, I'll assign others to do this for now.

OK krub 🙏Sorry for an inconvenient.
