### ISSUE TITLE
Add Members of Cabinet section

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#70]
Load cabinet member data (people) and show their positions.

## Edited

1. Filter people with `is_cabinet === true`
2. Unwind from `cabinet_position[]` to generate name-position tuple list. 
  **Note:** a person may has more than 1 positions.
3. Group by `cabinet_position`, then sort sections as follows:
  3.1 นายกรัฐมนตรี (Prime minister section)
  3.2 รองนายกรัฐมนตรี (Deputy prime minister section)
  3.3... กระทรวง XXX (Ministry of XXX section)
    - where XXX starting from ก - ฮ in Thai alphabetical order.
4. Card for each member should show only his/her name. The sample image below is incorrectly showing extraneous parties and party list numbers

![Screenshot_2019-11-03 Politician Directory Preview Mode - InVision(16)](https://user-images.githubusercontent.com/924635/68083022-957ab400-fe56-11e9-86db-d88618d6da77.png)

**Comment by Wisawing** [comment]
I'll try doing this one.

**Comment by Wisawing** [comment]
Is `สส.บัญชีรายชื่อลำดับที่ 1` coming from mp_type?
In that case, I only see `บัญชีรายชื่อ` and `แบ่งเขต` so I'm assuming `บัญชีรายชื่อ` will always be `สส.บัญชีรายชื่อลำดับที่ 1`. What will it be for `แบ่งเขต`

**Comment by rapee** [comment]
Hi @Wisawing 

After revising this infomation with data team, we'll show only the name-lastname of the member.

Please ignore `สส.บัญชีรายชื่อลำดับที่` parts. See added details in the issue description.

**Comment by Wisawing** [comment]
Two more questions:
- Where do I get images for people? Or should I just use a place holder for now?
- From the screenshot, I'm assuming it's categorized by ministry. However the data we have in `people.yaml` only have cabinet_position. It's possible to derived ministry from the postion however codewise it will be a bit ugly. Is that what's expected?

**Comment by rapee** [comment]
- Build URL with their name and lastname. Look for example in people-template.js
- That’s what’s expected. This is the first version of website and we’re learning while building. So data is not very nice for now.
