### ISSUE TITLE
Add profile section to Cabinet, Senate and House of Rep. pages

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#71]
Add profile section and bind data from GraphQL as needed.

Reuse component created in #66

Cabinet 
![Screenshot_2019-11-03 Politician Directory Preview Mode - InVision(16) copy 2](https://user-images.githubusercontent.com/924635/68083107-86e0cc80-fe57-11e9-9cbd-3591573fcf9c.png)

Senate
![Screenshot_2019-11-03 Politician Directory Preview Mode - InVision(18) copy](https://user-images.githubusercontent.com/924635/68083106-86e0cc80-fe57-11e9-9e33-ef6138e34e8f.png)

House of Representatives
![Screenshot_2019-11-03 Politician Directory Preview Mode - InVision(17) copy](https://user-images.githubusercontent.com/924635/68083109-8ba58080-fe57-11e9-877c-d52cdbe9738f.png)

Mobile

![Screenshot_2019-11-13 Politician Directory Preview Mode - InVision](https://user-images.githubusercontent.com/924635/68741709-f0fc2d00-0620-11ea-96ed-458b21e0995d.png)

**Comment by tanat44** [comment]
i am working on this issue
