### ISSUE TITLE
Add people's active status

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#72]
In people page, create <PeopleStatus /> component and bind data from **src/contents/people.yml** (`is_active`)

true = อยู่ในตำแหน่ง
false = พ้นจากตำแหน่ง

Active
<img width="417" alt="Screen Shot 2019-11-03 at 16 34 46" src="https://user-images.githubusercontent.com/924635/68083175-72e99a80-fe58-11e9-8162-cc2d08ae6c88.png">

Inactive
<img width="447" alt="Screen Shot 2019-11-03 at 16 34 50" src="https://user-images.githubusercontent.com/924635/68083157-39189400-fe58-11e9-9db2-36777d9fe213.png">

**Comment by noimeta** [comment]
@rapee how could i go to people page from main page?

**Comment by rapee** [comment]
Go to Home page > Choose party > Click on people card @noimeta

**Comment by rapee** [comment]
Since you were asking, I assigned you to this issue :D @noimeta
