### ISSUE TITLE
Add content to About page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#73]
![Screenshot_2019-11-03 Politician Directory Preview Mode - InVision(20)](https://user-images.githubusercontent.com/924635/68083246-19ce3680-fe59-11e9-9f40-b46695b41e98.png)

**Comment by p16i** [comment]
This is an idea for the "View this project on Github" button.  Maybe on this page, we should have a section convincing people to participate in the development of this project. I'm not sure exactly what kind of wording we should use. 

We might also have to write contribution guidelines.

**Comment by rapee** [comment]
Good idea, will be added.

**Comment by rapee** [comment]
@tanat44 Can you take this?

**Comment by tanat44** [comment]
> @tanat44 Can you take this?

Thanks. I will take care this issue.
