### ISSUE TITLE
Create VoteLog list page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#74]
Create VoteLog (บันทึกมติ) page (`/votelog`) to list all vote logs.

Bind data from `votelog.yml` ~and `people_vote.yml`~.

## Edited

Add dynamic pagination.

- No page reload when click to next pages. Scroll to top of the list and show new list content
- If possible, bind current page with query string e.g. `/votelog?page=2`.
- Resume to page from query string on page load.

![Screenshot_2019-11-03 Politician Directory Preview Mode - InVision(21)](https://user-images.githubusercontent.com/924635/68083272-5ef26880-fe59-11e9-8346-8227fd068f68.png)

**Comment by mixth** [comment]
Hi @rapee. It seems like this page needs only `votelog.yml`, doesn't it?

**Comment by rapee** [comment]
@mixth Yep, my mistake. Because we already have aggregated values in `votelog.yml`.

**Comment by rapee** [comment]
As discussed in #84, I think we need dynamic pagination.

The priority is low, though.

**Comment by rapee** [comment]
Will close this as it achieved what we needed.
