### ISSUE TITLE
Create VoteLog detail view page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#75]
Create Votelog details view page (`/votelog/4`).

Bind data from `votelog.yml` and `people_vote.yml`.

Example:

1)
![Screenshot_2019-11-03 Politician Directory Preview Mode - InVision(22)](https://user-images.githubusercontent.com/924635/68083298-b09af300-fe59-11e9-8c55-05aa5c581f7d.png)

2)
![Screenshot_2019-11-03 Politician Directory Preview Mode - InVision(23)](https://user-images.githubusercontent.com/924635/68083301-b42e7a00-fe59-11e9-986a-7af86f633191.png)

**Comment by thasarito** [comment]
I'm working on this!
