### ISSUE TITLE
Sort MP on party page

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#79]
Sort MP when

0. All - sort by MP name (Thai alphabetical order)
1. Party List - sort by party list in ascending order (1, 2, 3, ...)
2. District - sort by province name (กระบี่,​ กรุงเทพมหานคร, กาญจนบุรี, ...), then zone number (1, 2, 3, ...)

[Edited]
Home page
3. Sort parties (coalition & opposition) by number of seats.

<img width="1045" alt="Screen Shot 2019-11-04 at 22 54 12" src="https://user-images.githubusercontent.com/924635/68135630-9266ed00-ff56-11e9-9575-56c55c5a4b34.png">

**Comment by p16i** [comment]
We should also sort parties on the front page, i.e. by number of seats.

**Comment by rapee** [comment]
I updated issue details above. Don't think we need another issue for this.

**Comment by rapee** [comment]
Can you take this? @noimeta

**Comment by noimeta** [comment]
> Can you take this? @noimeta

ok!!
